# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DatabaseTutorial' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DatabaseTutorial
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target '<Your Target Name>' do
    pod 'Alamofire', '~> 4.5'

  

end
